
version: 2

sources:
    - name: staging
      database: service-calls-dev # project
      schema: service_calls_models # dataset
      tables: 
        - name: facts_2023_partitioned
        - name: city_wards_map
      

models:
    - name: stg_service_calls
      description: >
        Service request calls made in the city of Toronto
      columns:
          - name: Status
            description: "One of {Initiated, In Progress, Canceled, Closed}"
            tests:
              - accepted_values:
                  values:
                    - "Initiated"
                    - "In Progress"
                    - "Canceled"
                    - "Closed"
                  severity: warn
          - name: ward_name
            description: "Municipal electoral ward"
            tests:
              - not_null:
                  severity: warn
              - relationships:
                  field: Ward_Name
                  to: ref('ward_id_lookup')
          - name: ward_id
            description: "Numerical ID for ward name"
            tests:
              - relationships:
                  field: Ward_Number
                  to: ref('ward_id_lookup')
          - name: Service_Request_Type
            description: Nature of the service call request
            tests:
              - not_null:
                  severity: warn
          - name: creation_datetime
            description: "Datetime the service request was logged"
            tests:
              - not_null:
                  severity: warn
          - name: season
            description: "Meteorological season, according to the months only"
            tests:
              - accepted_values:
                  values: ['spring', 'summer', 'fall', 'winter']
    - name: stg_city_wards
      columns:
        - name: ward_name
          tests:
            - relationships:
                field: Ward_Name
                to: ref('ward_id_lookup')
        - name: ward_id
          tests:
            - relationships:
                field: Ward_Number
                to: ref('ward_id_lookup')
    
