steps:
# substitutions needed in the gcloud submit command:
#   _LOCATION, _REPOSITORY, _IMAGE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-f',
          'dockerfiles/Dockerfile.extract_load',
          '-t',
          '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_EL}',
          '--build-arg', 'GCP_PROJECT_ID=$PROJECT_ID',
          '--build-arg', 'BQ_DATASET=${_BQ_DATASET}',
          '--build-arg', 'GCS_BUCKET=${_GCS_BUCKET}',
          '--build-arg', 'SCRIPT_DIR=${_SCRIPT_DIR}',
          '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-f',
          'dockerfiles/Dockerfile.dbt',
          '-t',
          '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_T}',
          '--build-arg', 'GCP_PROJECT_ID=$PROJECT_ID',
          '--build-arg', 'BQ_DATASET=${_BQ_DATASET}',
          '--build-arg', 'DBT_PROJECT_DIR=${_DBT_PROJECT_DIR}',
          '.' ]

substitutions:
  # default values
  _LOCATION: us-west1
  _REPOSITORY: task-containers
  _BQ_DATASET: service_models
  _GCS_BUCKET: service-data-lake
  _DBT_PROJECT_DIR: ../dbt-core-service/
  _IMAGE_EL: extraction_load
  _IMAGE_T: dbt

# this step pushes to artifact registry
images: [
  '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_EL}',
  '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_T}'
]
