config:
  send_anonymous_usage_stats: false
  use_colors: true

service_calls_bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      threads: 4
      job_execution_timeout_seconds: 600
      job_retries: 3
      location: "{{ env_var('BQ_LOCATION') }}"
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      threads: 4
      job_execution_timeout_seconds: 600
      job_retries: 3
      location: "{{ env_var('BQ_LOCATION') }}"
      keyfile: "{{ env_var('KEYFILE_LOCATION') }}"
