FROM ghcr.io/dbt-labs/dbt-bigquery:1.5.0

ARG BQ_PROJECT_ID
ARG BQ_DATASET
ARG DBT_PROJECT_DIR

ENV DBT_PROJECT_DIR=$DBT_PROJECT_DIR
ENV BQ_PROJECT_ID=$BQ_PROJECT_ID
ENV BQ_DATASET=$BQ_DATASET

# default env values, can be overridden
ENV BQ_LOCATION="us-west1"
ENV DBT_PROFILES_DIR=/usr/app/
ENV TARGET=prod

COPY $DBT_PROJECT_DIR /usr/app/

# default entrypoint is already "dbt"
RUN dbt debug --target=$TARGET

ENTRYPOINT [ "dbt", "deps", "&&", "dbt", "run", "--target=$TARGET" ]
