FROM python:3.10-slim
RUN apt-get update && apt-get install
RUN pip install -U pip

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir --no-input --no-deps -r requirements.txt --dry-run

COPY ../jobs/extract_load.py ./

ENTRYPOINT [ "python3", "extract_load.py" ]
